#!/bin/bash
set -v -e
# tested with Amazon Linux 2023

# get admin privileges
sudo su

# disable ssm agent
systemctl stop amazon-ssm-agent
systemctl disable amazon-ssm-agent

# install packages
dnf update -y
dnf install -y jq
jq --version
dnf install -y httpd.x86_64

# populate default page
cat >> /var/www/html/index.html <<!
<title>Hello World</title>
<h1>Public App</h1> 
<p>This page content was generated by EC2 user data</p>
<pre>
{
    "hello": "world",
    "from": "quicklab.io"
}
</pre>
<br>
<hr>
<br> 
$(hostname -f)
<br>
!

# enable and start service
sudo systemctl enable httpd.service 
sudo systemctl start httpd.service
sudo systemctl status httpd.service

# give ec2-user permissions to modify apache
usermod -a -G apache ec2-user
chown -R ec2-user:apache /var/www
chmod 2775 /var/www

# add group write permissions and to set the group ID on future subdirectories
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;

# create output logs
output : { all : '| tee -a /var/log/cloud-init-output.log' }
